# Generated by Django 5.1.1 on 2024-10-18 21:20

from django.db import migrations


def fill_book_editions(apps, schema_editor):
    Book = apps.get_model('core', 'Book')
    BookEdition = apps.get_model('core', 'BookEdition')

    for book in Book.objects.all():
        BookEdition(book=book).save()


def migrate_reading_logs_data(apps, schema_editor):
    ReadingLog = apps.get_model('core', 'ReadingLog')

    for reading_log in ReadingLog.objects.all():
        reading_log.book_edition = reading_log.book.editions.first()
        reading_log.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_book_isbn_remove_book_publication_year_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_book_editions),
        migrations.RunPython(migrate_reading_logs_data),
    ]
