version: '3.8'

services:
  app:
    env_file: .env
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_ENGINE=${DATABASE_ENGINE}
      - POSTGRES_HOST=${DATABASE_HOST}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_DB}
    depends_on:
      - db

  nginx:
    env_file: .env
    image: nginx:1.25
    ports:
      - "51100:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../static:/app/static
    depends_on:
      - app

  db:
    env_file: .env
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
      - E:\private_library\dumps:/dumps
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_DB}

volumes:
  pgdata:
