# Generated by Django 5.1.1 on 2024-10-08 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title_original',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='readinglog',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reading_logs', to='core.book'),
        ),
        migrations.AlterField(
            model_name='readinglog',
            name='year_finish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='year_finish', to='core.year'),
        ),
        migrations.AlterField(
            model_name='readinglog',
            name='year_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='year_start', to='core.year'),
        ),
    ]
