# Generated by Django 5.1.1 on 2024-10-18 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reading_log_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinglog',
            name='book',
        ),
        migrations.AlterField(
            model_name='readinglog',
            name='book_edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reading_logs', to='core.bookedition'),
        ),
    ]
