# Generated by Django 5.1.1 on 2026-02-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedition',
            name='edition_type',
            field=models.CharField(
                choices=[
                    ('PAPER_BOOK', 'Paper Book'),
                    ('EBOOK', 'E-book'),
                    ('AUDIOBOOK', 'Audiobook'),
                    ('WEBPAGE', 'Web Page')
                ],
                default='PAPER_BOOK',
                help_text="Type of book edition",
                max_length=20,
                null=False,
                blank=False,
            ),
        ),
    ]
