# Generated by Django 5.1.1 on 2026-02-18 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_keyword_note_notetobookedition'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='descendants', to='core.note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.note'),
        ),
    ]
